version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
